# Generated by Django 5.0.7 on 2024-08-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_conversation_title_alter_conversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='meta_data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
