# Generated by Django 5.0.7 on 2024-08-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_meta_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ai_response_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_response_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
