# Generated by Django 5.0.7 on 2024-08-19 12:06

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_ai_response_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=26, prefix='msg_', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=27, prefix='conv_', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=27, prefix='sess_', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chat.conversation')),
            ],
        ),
    ]
