name: beaconmind 

services:
  db:
    image: postgres:16.3-alpine3.20
    networks:
      - proxy
    restart: always
    env_file:
      - ./db/.env
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data

  beacon:
    image: ghcr.io/atharv-naik/beacon:staging
    networks:
      - proxy
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
    command: sh  -c "python manage.py migrate --noinput && gunicorn beaconmind.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file: 
      - ./app/.env.prod
    volumes:
      - static:/app/static
      - pg-data:/var/lib/postgresql/data
    depends_on:
      db:
        condition: service_healthy

volumes:
  static:
  pg-data:

networks:
  proxy:
    name: proxy
