# Generated by Django 5.0.7 on 2024-08-19 12:06

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_doctor_remove_user_is_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=26, prefix='doc_', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=26, prefix='pat_', primary_key=True, serialize=False),
        ),
    ]
