# Generated by Django 5.0.7 on 2024-11-04 10:12

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_doctor_id_alter_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PHQ9Assessment',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=29, prefix='assess_', primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phq9_assessment', to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PHQ9Question',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=24, prefix='q_', primary_key=True, serialize=False)),
                ('question_id', models.IntegerField()),
                ('question_text', models.CharField(default='', max_length=255)),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.phq9assessment')),
            ],
        ),
        migrations.CreateModel(
            name='PHQ9Score',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=28, prefix='score_', primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='accounts.phq9assessment')),
            ],
        ),
    ]
