# Generated by Django 5.0.7 on 2024-12-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_phq9assessment_phq9question_phq9score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PHQ9Assessment',
            new_name='Assessment',
        ),
        migrations.RenameModel(
            old_name='PHQ9Question',
            new_name='AssessmentRecord',
        ),
        migrations.RenameModel(
            old_name='PHQ9Score',
            new_name='AssessmentResult',
        ),
    ]
