# Generated by Django 5.0.7 on 2024-12-19 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_phq9assessment_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('phq9', 'PHQ9')], default='phq9', max_length=10),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='severity',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('mild', 'Mild'), ('moderate', 'Moderate'), ('moderately-severe', 'Moderately Severe'), ('severe', 'Severe')], default='minimal', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='accounts.patient'),
        ),
    ]
