# Generated by Django 5.0.7 on 2025-01-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_assessment_type_assessmentresult_severity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='assessmentrecord',
            name='assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentResult',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='AssessmentRecord',
        ),
    ]
