# Generated by Django 5.0.7 on 2025-01-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_assessment_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phase',
            field=models.CharField(default='assessment.phq9', max_length=48),
        ),
    ]
