# Generated by Django 5.0.7 on 2025-01-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_patient_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phase',
            field=models.CharField(default='assessment.phq9', max_length=30),
        ),
    ]
