# Generated by Django 5.0.7 on 2025-02-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_patient_phase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="Anonymous", max_length=30),
        ),
    ]
