# Generated by Django 5.0.7 on 2025-03-15 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": [("can_access_dashboard", "Can access dashboard")]},
        ),
    ]
