# Generated by Django 5.0.7 on 2025-03-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="receive_patient_alerts",
            field=models.BooleanField(default=False),
        ),
    ]
