# Generated by Django 5.0.7 on 2025-03-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_doctor_receive_patient_alerts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"permissions": [("can_access_dashboard", "Can access dashboard")]},
        ),
    ]
