# Generated by Django 5.0.7 on 2025-03-15 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_access_dashboard", "Can access dashboard"),
                    ("can_perform_chat", "Can perform chat"),
                    ("can_view_chat_session", "Can view chat session"),
                ]
            },
        ),
    ]
