# Generated by Django 5.0.7 on 2025-03-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="phase",
        ),
    ]
