# Generated by Django 5.0.7 on 2025-01-02 14:59

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentrecord',
            options={'verbose_name': 'Assessment Record', 'verbose_name_plural': 'Assessment Records'},
        ),
        migrations.AlterModelOptions(
            name='assessmentresult',
            options={'verbose_name': 'Assessment Result', 'verbose_name_plural': 'Assessment Results'},
        ),
        migrations.AddField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=26, prefix='rec_', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=22, max_length=26, prefix='res_', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
