# Generated by Django 5.0.7 on 2025-01-03 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessmentrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentrecord',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='assessments.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.assessment'),
        ),
    ]
