# Generated by Django 5.0.7 on 2025-01-04 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_patient_phase'),
        ('assessments', '0003_alter_assessmentrecord_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='accounts.patient'),
        ),
        migrations.AlterField(
            model_name='assessmentrecord',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='assessments.assessment'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.assessment'),
        ),
    ]
