# Generated by Django 5.0.7 on 2025-01-15 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessment_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('assessment.phq9', 'PHQ9')], default='assessment.phq9', max_length=30),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.assessment'),
        ),
    ]
