# Generated by Django 5.0.7 on 2025-01-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_alter_assessment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentrecord',
            name='dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='snippets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('assessment.phq9', 'PHQ9'), ('assessment.gad7', 'GAD7')], default='assessment.phq9', max_length=30),
        ),
    ]
