# Generated by Django 5.0.7 on 2025-01-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assessmentrecord_dirty_assessmentrecord_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Started at'),
        ),
    ]
