# Generated by Django 5.0.7 on 2025-01-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_assessment_completed_at_alter_assessment_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentrecord',
            old_name='remarks',
            new_name='remark',
        ),
        migrations.RenameField(
            model_name='assessmentrecord',
            old_name='snippets',
            new_name='snippet',
        ),
    ]
