# Generated by Django 5.0.7 on 2025-02-06 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0009_alter_assessment_type"),
        ("chat", "0011_chatsession_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="chat.chatsession",
            ),
        ),
    ]
