# Generated by Django 5.0.7 on 2025-02-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0010_assessment_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("aborted", "Aborted"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
