# Generated by Django 5.0.7 on 2025-02-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0011_alter_assessment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="type",
            field=models.CharField(
                choices=[
                    ("assessment.phq9", "PHQ9"),
                    ("assessment.gad7", "GAD7"),
                    ("monitoring", "Monitoring"),
                    ("assessment.asq", "ASQ"),
                ],
                default="assessment.phq9",
                max_length=30,
            ),
        ),
    ]
