# Generated by Django 5.0.7 on 2025-02-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0012_alter_assessment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentrecord",
            name="question_id",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
