# Generated by Django 5.0.7 on 2024-08-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatmessage_id_alter_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chat_session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession'),
        ),
    ]
