# Generated by Django 5.0.7 on 2024-09-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatmessage_chat_session'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
    ]
