# Generated by Django 5.0.7 on 2024-12-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ai_marker',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='user_marker',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
