# Generated by Django 5.0.7 on 2025-01-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatmessage_ai_marker_chatmessage_user_marker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Chat Message', 'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['timestamp'], 'verbose_name': 'Chat Session', 'verbose_name_plural': 'Chat Sessions'},
        ),
    ]
