# Generated by Django 5.0.7 on 2025-01-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chatmessage_options_alter_chatsession_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='ai_marker',
            field=models.JSONField(default=dict, null=True, verbose_name='AI marker'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='ai_response',
            field=models.TextField(default='', null=True, verbose_name='AI response'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='ai_response_timestamp',
            field=models.DateTimeField(null=True, verbose_name='AI response timestamp'),
        ),
    ]
