# Generated by Django 5.0.7 on 2025-02-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_alter_chatmessage_ai_marker_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("aborted", "Aborted"),
                ],
                default="open",
                max_length=10,
            ),
        ),
    ]
