# Generated by Django 5.0.7 on 2025-02-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_chatsession_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="INIT",
            field=models.BooleanField(default=False, verbose_name="INIT"),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="last_msg",
            field=models.TextField(
                default=None, null=True, verbose_name="Last Message"
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="node_id",
            field=models.CharField(
                default=None, max_length=10, null=True, verbose_name="Question Node ID"
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="phase",
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="retries",
            field=models.IntegerField(default=0),
        ),
    ]
