# Generated by Django 5.0.7 on 2025-02-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_chatsession_init_chatsession_last_msg_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatsession",
            old_name="INIT",
            new_name="init",
        ),
    ]
