# Generated by Django 5.0.7 on 2025-03-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_rename_init_chatsession_init"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "get_latest_by": "timestamp",
                "ordering": ["timestamp"],
                "verbose_name": "Chat Session",
                "verbose_name_plural": "Chat Sessions",
            },
        ),
    ]
